name: Backend Build and push to GitHub Container Registry

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  # HARBOR_REG_URL: 'harbor.k8k8kk88.win'
  # HARBOR_PROJECT_NAME: backend
  IMAGE_NAME: helmchart-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 设置时间格式 (yyyyMMddHHmmss)
      - name: Set formatted timestamp (Shanghai Time)
        id: timestamp
        run: |
          echo "TIMESTAMP=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      # 设置 Docker 标签
      - name: Set Docker tags
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ env.TIMESTAMP }}" >> $GITHUB_ENV
          fi

      # Log into GitHub Container Registry
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Log into Private Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: harbor.k8k8kk88.win
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ env.HARBOR_REG_URL }}/${{ env.HARBOR_PROJECT_NAME }}/${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}

      # Build and push to GitHub Container Registry
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
      
      # Make the package public
      - name: Make package public
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}      # 或 ${{ secrets.PKG_TOKEN }}（视权限而定）
          ORG: yaencn           # 替换为你的 GitHub 组织名称
          TYPE: container                       # npm, maven, rubygems, nuget, container
          NAME: ${{ env.IMAGE_NAME }}                       # package 名称或镜像名
        run: |
          set -e
          curl -s -o /dev/null -w "%{http_code}" \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"visibility":"public"}' \
            "https://api.github.com/orgs/${ORG}/packages/${TYPE}/${NAME}/visibility" \
          || (echo "Failed to set visibility" && exit 1)